### ISSUE TITLE
The website sigmaclient.info can't view

### ISSUE THREAD

**Issue by yangnuozhen** [sigmaclient/SigmaClient#4]
[This](https://sigmaclient.info/) is your website,right?
But it CAN'T view now!!!
Also,when I trying to open the sigma client,it crashed and print:
```
java.io.FileNotFoundException: https://jelloprg.sigmaclient.info/download/prelauncher/version
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1896)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at info.sigmaclient.jellobootstrap.JelloBootstrap.queryUrl(JelloBootstrap.java:65)
	at info.sigmaclient.jellobootstrap.JelloBootstrap.<init>(JelloBootstrap.java:35)
	at info.sigmaclient.jellobootstrap.JelloBootstrap.main(JelloBootstrap.java:18)
java.lang.ClassNotFoundException: info.sigmaclient.jelloprelauncher.JelloPrelauncher
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at info.sigmaclient.jellobootstrap.JelloBootstrap.launchPrelauncher(JelloBootstrap.java:104)
	at info.sigmaclient.jellobootstrap.JelloBootstrap.<init>(JelloBootstrap.java:40)
	at info.sigmaclient.jellobootstrap.JelloBootstrap.main(JelloBootstrap.java:18)
```
I try to visit the website `https://jelloprg.sigmaclient.info/download/prelauncher/version` ,but there was only Apache2 Debian Default Page!
Please tell us what happend.

**Comment by JonnyOnline** [comment]
Punjabi monero skid clarinet dev gave Up
But i never gonna give you Up and Never gonna let you down

**Comment by Reycko** [comment]
dont try anyways, sigma has a Bitcoin miner on the source code

**Comment by yangnuozhen** [comment]
wow

**Comment by TheMosKau** [comment]
> dont try anyways, sigma has a Bitcoin miner on the source code

sigma hator
